# Generated by Django 5.2.2 on 2025-06-05 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserIndex",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("unique_name", models.CharField(max_length=150, unique=True)),
                ("username", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_id", models.CharField(max_length=50)),
                ("company_name", models.CharField(max_length=100)),
                ("buy_quantity", models.PositiveIntegerField()),
                ("buy_price", models.DecimalField(decimal_places=6, max_digits=100)),
                ("buy_date", models.DateField()),
                (
                    "current_price",
                    models.DecimalField(decimal_places=6, max_digits=100),
                ),
                (
                    "total_investment",
                    models.DecimalField(decimal_places=4, max_digits=100),
                ),
                ("sold_quantity", models.PositiveIntegerField(default=0)),
                (
                    "sold_price",
                    models.DecimalField(decimal_places=6, default=0.0, max_digits=100),
                ),
                ("sold_date", models.DateField(blank=True, null=True)),
                (
                    "todays_profit_loss",
                    models.DecimalField(decimal_places=6, default=0.0, max_digits=100),
                ),
                (
                    "profit_loss",
                    models.DecimalField(decimal_places=6, default=0.0, max_digits=100),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="app.userindex"
                    ),
                ),
            ],
        ),
    ]
